import Head from 'next/head'
import { HomePage } from '../src/components/home'
import { About } from '../src/components/about'
import { Skills } from '../src/components/skills'
import { SkillsPhone } from '../src/components/skillsPhone'
import { Resume } from '../src/components/resume'
import { Project } from '../src/components/project'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomePage/>
        <About/>
        <Skills/>
        <SkillsPhone/>
        <Resume/>
        <Project/>
      </main>
    </>
  )
}
